[package]
name = "alidevs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
yew-router = { git = "https://github.com/yewstack/yew.git" }

